[package]

name = "typemap"
version = "0.0.10"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
license = "MIT"
description = "A typesafe store for many value types."
repository = "https://github.com/reem/rust-typemap"

[dependencies]
unsafe-any = "*"

